# Numpy

NumPy es un paquete fundamental para la programación científica que __proporciona un objeto tipo array__ para almacenar datos de forma eficiente y una serie de __funciones__ para operar y manipular esos datos.
Para usar NumPy lo primero que debemos hacer es importarlo:

<img src="https://aprendeconalf.es/docencia/python/manual/img/numpy-logo.png">

In [1]:
# Importar numpy para manejo de matrices
import numpy as np
print(np.__version__)

# Si no estuviese instalado el paquete numpy usar la sentencia --> pip install numpy

1.19.4


Un array es un __bloque de memoria que contiene elementos del mismo tipo__. Básicamente:

* nos _recuerdan_ a los vectores, matrices, tensores...
* podemos almacenar el array con un nombre y acceder a sus __elementos__ mediante sus __índices__.
* ayudan a gestionar de manera eficiente la memoria y a acelerar los cálculos.


---

| Índice     | 0     | 1     | 2     | 3     | ...   | n-1   | n  |
| ---------- | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| Valor      | 2.1   | 3.6   | 7.8   | 1.5   | ...   | 5.4   | 6.3 |

---

__¿Qué solemos guardar en arrays?__

* Vectores y matrices.
* Datos de experimentos:
    - En distintos instantes discretos.
    - En distintos puntos del espacio.
* Resultado de evaluar funciones con los datos anteriores.
* Discretizaciones para usar algoritmos de: integración, derivación, interpolación...


<img src="https://aprendeconalf.es/docencia/python/manual/img/arrays.png">

## Creación de Arrays

Usaremos la sentencia **np.array(lista)** de la siguiente manera:

-Para una lista de valores se crea un array de una dimensión, también conocido como **vector**.  
-Para una lista de listas de valores se crea un array de dos dimensiones, también conocido como **matriz**.  
-Para una lista de listas de listas de valores se crea un array de tres dimensiones, también conocido como **cubo**.  
Y así sucesivamente. No hay límite en el número de dimensiones del array más allá de la memoria disponible en el sistema.

In [2]:
# Array de una dimensión
a1 = np.array([1, 2, 3])
print(a1)

[1 2 3]


In [3]:
# Array de dos dimensiones
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [4]:
# Array de tres dimensiones
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [5]:
# Array de ceros en una dimension
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
# Array de ceros en dos dimensiones
np.zeros([2, 5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
# Array de unos en dos dimensiones
np.ones([3, 2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Matriz identidad
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
# Mediante rangos
a = np.arange(0, 5)
print(a)
b = np.arange(0, 12, 3)
print(b)

[0 1 2 3 4]
[0 3 6 9]


In [18]:
# Matriz mediante intervalos
intervalos = np.linspace(0, 10, 5)
print(intervalos)

[ 0.   2.5  5.   7.5 10. ]


In [10]:
# Creando array vacio
vacia = np.empty((3,2))
print(vacia)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [13]:
# creando array de numeros aleatorios
aleatorios = np.random.random((2,2))
print(aleatorios)

[[0.49323058 0.68018034]
 [0.07382035 0.34151894]]


In [16]:
# Matriz con valores iguales
full = np.full((3,4), 5)
print(full)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


## Atributos de un Array

In [23]:
# Número de dimensiones de un array
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [24]:
# Dimensiones de un array
print(a1.shape)
print(a2.shape)
print(a3.shape)

(3,)
(2, 3)
(2, 2, 3)


In [25]:
# Numero de Elemntos de un array
print(a1.size)
print(a2.size)
print(a3.size)

3
6
12


In [26]:
# Numero de Elemntos de un array
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
int32
int32


## Operaciones con Arrays

In [27]:
#crear un arra y y sumarle un número
arr = np.arange(11)
print(arr)
arr + 55

[ 0  1  2  3  4  5  6  7  8  9 10]


array([55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65])

In [28]:
#multiplicarlo por un número
print(arr)
arr * 2

[ 0  1  2  3  4  5  6  7  8  9 10]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [29]:
#elevarlo al cuadrado
print(arr)
arr ** 2

[ 0  1  2  3  4  5  6  7  8  9 10]


array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [30]:
#calcular una función
print(arr)
np.tanh(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


array([0.        , 0.76159416, 0.96402758, 0.99505475, 0.9993293 ,
       0.9999092 , 0.99998771, 0.99999834, 0.99999977, 0.99999997,
       1.        ])

In [32]:
# También podemos hacer operaciones entre dos arrays
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1, 1], [2, 2, 2]])
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 1 1]
 [2 2 2]]


In [33]:
print(a + b )
print(a / b)
print(a ** 2)

[[2 3 4]
 [6 7 8]]
[[1.  2.  3. ]
 [2.  2.5 3. ]]
[[ 1  4  9]
 [16 25 36]]


In [34]:
# Multiplicacion de Matrices (mxn vs nxp)
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1], [2, 2], [3, 3]])
print(a)
print(b)
print("El resultado es: ")
print(a.dot(b))

[[1 2 3]
 [4 5 6]]
[[1 1]
 [2 2]
 [3 3]]
El resultado es: 
[[14 14]
 [32 32]]


In [35]:
# Transpuesta de una matriz
print(a.T)

[[1 4]
 [2 5]
 [3 6]]


In [41]:
# Inversa de una matriz
arr = np.array([[1, 3], [5, 7]])
print(arr)
arr_inv = np.linalg.inv(arr)
print(arr_inv)

[[1 3]
 [5 7]]
[[-0.875  0.375]
 [ 0.625 -0.125]]


## Reshape

Con `np.arange()` es posible crear "vectores" cuyos elementos tomen valores consecutivos o equiespaciados, como hemos visto anteriormente. ¿Podemos hacer lo mismo con "matrices"? Pues sí, pero no usando una sola función. Imagina que quieres crear algo como esto:

\begin{pmatrix}
    1 & 2 & 3\\ 
    4 & 5 & 6\\
    7 & 8 & 9\\
\end{pmatrix}
    
* Comenzaremos por crear un array 1d con los valores $(1,2,3,4,5,6,7,8,9)$ usando `np.arange()`.
* Luego le daremos forma de array 2d. con `np.reshape(array, (dim0, dim1))`.

In [42]:
a = np.arange(1, 10)
print(a)
M = np.reshape(a, [3, 3])
M

[1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
# tambien funciona de esta manera
a.reshape([3,3])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Acesso a los elementos

Para ello se usa la sintaxis `inicio:final:paso`: si alguno de estos valores no se pone toma un valor por defecto. Veamos ejemplos:

In [45]:
# Una dimension
arr1 = np.arange(0, 11)
print(arr1)
print(arr1[2:7])
print(arr1[2:10:2])

[ 0  1  2  3  4  5  6  7  8  9 10]
[2 3 4 5 6]
[2 4 6 8]


In [46]:
# Dos dimensiones
print(M)
print("1.-\n", M[:2])
print("2.-\n", M[:2, 1])
print("3.-\n", M[:2, 2])
print("4.-\n", M[:2, 1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1.-
 [[1 2 3]
 [4 5 6]]
2.-
 [2 5]
3.-
 [3 6]
4.-
 [[2 3]
 [5 6]]


# Ejercicios

In [ ]:
# Resuleva la matriz de la primera imagen


In [ ]:
# Resuleva la matriz de la segunda imagen
